### ISSUE TITLE
CI/CD Pipeline For Cobol

### ISSUE THREAD

**Issue by varshadhanashree** [jellypuno/Cobol-Made-Easy#1]
Need to understand build process for COBOL

**Comment by jellypuno** [comment]
@varshadhanashree Will these blogs help?

https://medium.com/modern-mainframe/beginners-guide-cobol-made-easy-leveraging-open-source-tools-eb4f8dcd7a98
https://medium.com/modern-mainframe/how-i-used-typescript-to-generate-my-cobol-programs-a2a180209148
https://youtu.be/u8Nujk1swDI
https://youtu.be/6mLvVNYuyp8

**Comment by varshadhanashree** [comment]
Hello 
I have gone through this blogs Thank You So Much
I want steps to build COBOL in Azure DevOps

**Comment by jellypuno** [comment]
@varshadhanashree I see. I am not familiar with that use case but I hope the blogs could help 👍

**Comment by varshadhanashree** [comment]
Okay No issues  Thank you
